library identifier: 'pipeline-shared-libs@master', retriever: modernSCM(
        [$class: 'GitSCMSource', remote: 'git@github.com:pmahajan-ee/pipeline-shared-libs.git'])

albAndDnsCreatePipeline {
    env = "dev"
    vpc = "dev-ecs-workshop"
    user_unique_name = "paresh"
    github_user_or_org = "pmahajan-ee"
}